### ISSUE TITLE
No Github link on readthedocs

### ISSUE THREAD

**Issue by joooeey** [nineteendo/jsonyx#10]
The documentation currently online at https://jsonyx.readthedocs.io/ [doesn't include an easy to find](https://www.google.com/search?q=github+site%3Ajsonyx.readthedocs.io&oq=github+site%3Ajsonyx.readthedocs.io&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCDYwOTBqMGoxqAIAsAIA&sourceid=chrome&ie=UTF-8) link to this repository here on Github. The only links to Github is the button with the pytest pipeline (`pytest | passing`).

**Comment by nineteendo** [comment]
Does the latest documentation look better? https://jsonyx.readthedocs.io/en/latest.

**Comment by joooeey** [comment]
Definitely better but on most readthedocs pages, the link to github is in the top right where it says "View page source" in the link I gave in the OP. Perhaps adding `"conf_py_path": "/source/"` to the `html_context` in https://github.com/nineteendo/jsonyx/blob/main/docs/source/conf.py will fix it?

**Comment by nineteendo** [comment]
The theme I'm using displays that as buttons. The link to GitHub is also in the sidebar and footer.
This is like https://docs.pytest.org does it. If you're expecting in another place let me know.
Hopefully the GitHub repository gets ranked higher in the search results.

**Comment by nineteendo** [comment]
Maybe you didn't dismiss the version warning?

**Comment by nineteendo** [comment]
I'm closing this, let me know if you have further suggestions.
