### ISSUE TITLE
Add package to conda

### ISSUE THREAD

**Issue by joooeey** [nineteendo/jsonyx#9]
Most of the scientific community uses `conda`/`mamba` for package management instead of `pip`. Hence it would be sweet to make this package available on one of the `conda` channels.

AFAIK the best-maintained channel is `conda-forge`. At least that's where I would share a package if I had one. [Instructions for contributing a package to `conda-forge` are here.](https://conda-forge.org/docs/maintainer/adding_pkgs/)

**Comment by nineteendo** [comment]
Thanks for the instructions, I've created a pull request: https://github.com/conda-forge/staged-recipes/pull/27416

**Comment by nineteendo** [comment]
Done: https://anaconda.org/conda-forge/jsonyx

**Comment by joooeey** [comment]
Sweet! The corresponding docs also look great!

I just tried and successfully installed the package with `mamba install jsonyx`. Many of us have conda-forge set as the default channel.
